export const ASSET_KEYS = Object.freeze({
  BACKGROUND: 'BACKGROUND',
  FOREGROUND: 'FOREGROUND',
  PLATFORM: 'PLATFORM',
  ALIEN_GROUND_IDLE: 'ALIEN_GROUND_IDLE',
  ALIEN_GROUND_WALK: 'ALIEN_GROUND_WALK',
  ALIEN_FLYING_IDLE: 'ALIEN_FLYING_IDLE',
});

export const SCENE_KEYS = Object.freeze({
  LOADING_SCENE: 'LOADING_SCENE',
  GAME_SCENE: 'GAME_SCENE',
});
